// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Sp2.Persistence;

#nullable disable

namespace Sp2.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sp2.Models.Campaign", b =>
                {
                    b.Property<int>("id_campaing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_campaing");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_campaing"));

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("details");

                    b.Property<DateTime>("dt_register")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_register");

                    b.Property<int>("id_company")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("id_product")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nm_campaign")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_campaing");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("target");

                    b.HasKey("id_campaing");

                    b.HasIndex("id_company");

                    b.HasIndex("id_product");

                    b.ToTable("Campaign");
                });

            modelBuilder.Entity("Sp2.Models.Company", b =>
                {
                    b.Property<int>("id_company")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_company");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_company"));

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("dt_register")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_register");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("email");

                    b.Property<string>("nm_company")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_company");

                    b.HasKey("id_company");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Sp2.Models.Payhist", b =>
                {
                    b.Property<int>("id_history")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_history");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_history"));

                    b.Property<DateTime>("dt_due")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_due");

                    b.Property<DateTime>("dt_payment")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_payment");

                    b.Property<byte[]>("nfe")
                        .IsRequired()
                        .HasColumnType("RAW(2000)")
                        .HasColumnName("nfe");

                    b.Property<decimal>("value_pay")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("value_pay");

                    b.HasKey("id_history");

                    b.ToTable("Pay_hist");
                });

            modelBuilder.Entity("Sp2.Models.Paymethod", b =>
                {
                    b.Property<int>("id_method")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_method"));

                    b.Property<int>("id_history")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("id_sub")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("nm_method")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nm_method");

                    b.HasKey("id_method");

                    b.HasIndex("id_history");

                    b.HasIndex("id_sub");

                    b.ToTable("Pay_method");
                });

            modelBuilder.Entity("Sp2.Models.Product", b =>
                {
                    b.Property<int>("id_product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_product");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_product"));

                    b.Property<string>("category_product")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("category_product");

                    b.Property<string>("nm_product")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_product");

                    b.HasKey("id_product");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Sp2.Models.Profileuser", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_user");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_user"));

                    b.Property<DateTime>("dt_register")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_user");

                    b.Property<int>("id_company")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nm_user")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_user");

                    b.Property<string>("pass_user")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pass_user");

                    b.Property<string>("permission_user")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("permission_user");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status_user");

                    b.HasKey("id_user");

                    b.HasIndex("id_company");

                    b.ToTable("Profile_user");
                });

            modelBuilder.Entity("Sp2.Models.Subscriptioncompany", b =>
                {
                    b.Property<int>("id_sub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_sub");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_sub"));

                    b.Property<DateTime>("dt_end")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_end");

                    b.Property<DateTime>("dt_start")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_start");

                    b.Property<int>("id_company")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.Property<decimal>("value_sub")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("value_sub");

                    b.HasKey("id_sub");

                    b.HasIndex("id_company");

                    b.ToTable("Subscription_company");
                });

            modelBuilder.Entity("Sp2.Models.Campaign", b =>
                {
                    b.HasOne("Sp2.Models.Company", "Company")
                        .WithMany("Campaigns")
                        .HasForeignKey("id_company")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sp2.Models.Product", "Product")
                        .WithMany("Campaigns")
                        .HasForeignKey("id_product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sp2.Models.Paymethod", b =>
                {
                    b.HasOne("Sp2.Models.Payhist", "Payhist")
                        .WithMany("Pay_method")
                        .HasForeignKey("id_history")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sp2.Models.Subscriptioncompany", "Subscription_company")
                        .WithMany()
                        .HasForeignKey("id_sub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payhist");

                    b.Navigation("Subscription_company");
                });

            modelBuilder.Entity("Sp2.Models.Profileuser", b =>
                {
                    b.HasOne("Sp2.Models.Company", "Company")
                        .WithMany("Profile_users")
                        .HasForeignKey("id_company")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Sp2.Models.Subscriptioncompany", b =>
                {
                    b.HasOne("Sp2.Models.Company", "Company")
                        .WithMany("Subscriptionscompanies")
                        .HasForeignKey("id_company")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Sp2.Models.Company", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Profile_users");

                    b.Navigation("Subscriptionscompanies");
                });

            modelBuilder.Entity("Sp2.Models.Payhist", b =>
                {
                    b.Navigation("Pay_method");
                });

            modelBuilder.Entity("Sp2.Models.Product", b =>
                {
                    b.Navigation("Campaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
